//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utilities {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceTemplates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceTemplates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Utilities.ResourceTemplates", typeof(ResourceTemplates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;span style=&quot;font-size: large;&quot;&gt;Global Track Notification&lt;/span&gt;&lt;/p&gt;
        ///&lt;p&gt;New Tracking has been created.&amp;nbsp;&lt;/p&gt;
        ///&lt;p&gt;&lt;strong&gt;Service provider: &lt;/strong&gt;#ServiceProvider#&lt;/p&gt;
        ///&lt;p&gt;&lt;strong&gt;Tracking Item:&lt;/strong&gt;#TrackingItemName#&lt;/p&gt;
        ///&lt;p&gt;&lt;strong&gt;Current Status:&lt;/strong&gt;#Status#&lt;/p&gt;
        ///&lt;p&gt;&lt;strong&gt;Comment:&lt;/strong&gt;#Comment#&lt;/p&gt;
        ///&lt;p&gt;&lt;strong&gt;Tracking Number:&amp;nbsp;&lt;/strong&gt;#TrackingNumber#&lt;/p&gt;
        ///&lt;p&gt;&lt;strong&gt;Password: &lt;/strong&gt;#Password#&lt;/p&gt;
        ///&lt;p&gt;You may track the status of your order by visiting tracking service pa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NewTrackingNotificationTemplate {
            get {
                return ResourceManager.GetString("NewTrackingNotificationTemplate", resourceCulture);
            }
        }
    }
}
